### ISSUE TITLE
Test with larger dataset?

### ISSUE THREAD

**Issue by Tokkiu** [slow-steppers/NeighborHash#2]
Thanks for your hard work. The hash implementation is amazing and outperforms many hash maps in C++. 

By the way, do you guys have recommended settings with larger datasets (real industrial systems) and heavier hash collisions? 
etc, I can tell the default load factor is 0.8.

**Comment by wudisheng** [comment]
There might be no short answer.

We have been using NeighborHash-based KV services in our real industrial systems for years, and the configurations gurdually change over time along with data size, data characteristics and hardware specifications (including but not limited to CPU features, high performance block storage such as NVMe and network bandwidth, etc.). Typically, we often use sharding to split a large dataset (e.g. a huge table) into several pieces with appropriate sizes, while providing a client SDK for users to behave as a single one.

We'd be glad to discuss with you on some detailed sceanrios and do our best to make recommendations.

Also, @ZT-Alonzo for deep insights.

**Comment by ZT-Alonzo** [comment]
@Tokkiu Thank you for your interest in NeighborHash.

In production, we basically adopt the default policy in the code, using 12 bits from the value as metadata, a load factor of 0.8, huge pages, and absl::Hash. We haven't encountered significant conflict issues. 

For query interfaces, looking at upper-layer business needs, such as batch queries with amac+simd for model training/inference, point queries for scenarios with heavier business logic are more convenient. 

Due to NeighborHash minimizing memory access, the benefit of huge pages is greater compared to other hash maps. For instance, LinearProbing typically accesses more cache lines per average query, but since these cache lines often reside on the same page, memory reads are 1 (tlb miss) + n (probing cache lines). In contrast, NeighborHash results in 1 (tlb miss) + 1 (mostly), hence recommending huge pages in memory bandwidth-constrained scenarios. 

Lower load factors also improve performance slightly. If the memory overhead of hash index in the scenario is small, it can be set lower, but 0.8 can be considered a default recommended value.
